# Generated by Django 4.0 on 2023-02-10 04:56

import cnn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='title',
            field=models.CharField(default='nanashi', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=cnn.models.savePath),
        ),
    ]
