# Generated by Django 4.0 on 2023-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0002_uploadimage_title_alter_uploadimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(default='SOME STRING', upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gray', models.ImageField(default='Not Set', upload_to='')),
            ],
        ),
    ]
