# Generated by Django 4.0 on 2023-02-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0004_remove_document_gray_remove_document_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
